{
 "title": "Main",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Growing pairs total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (asset) (binance_growing_pairs_total)",
     "legendFormat": "{{asset}}"
    }
   ]
  },
  {
   "title": "Falling pairs total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (asset) (binance_falling_pairs_total)",
     "legendFormat": "{{asset}}"
    }
   ]
  },
  {
   "title": "Price didn't change total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (asset) (binance_same_price_pairs_total)",
     "legendFormat": "{{asset}}"
    }
   ]
  },
  {
   "title": "Growing pairs percent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (asset) (binance_growing_pairs_percent)",
     "legendFormat": "Percent of growing {{asset}} pairs"
    }
   ]
  },
  {
   "title": "Reddit Posts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (keyword) (reddit_posts_total)",
     "legendFormat": "{{keyword}}"
    }
   ]
  }
 ]
}