"""Create reddit_posts table

Revision ID: b2a598d1339d
Revises: 
Create Date: 2021-03-08 22:41:20.207003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a598d1339d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_posts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('reddit_kind', sa.String(length=2), nullable=False),
        sa.Column('reddit_id', sa.String(length=20), nullable=False),
        sa.Column('reddit_url', sa.String(), nullable=False),
        sa.Column('subreddit', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('reddit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reddit_posts')
    # ### end Alembic commands ###
