"""Create reddit_posts table

Revision ID: 8435d9ca9f56
Revises: 
Create Date: 2021-03-08 23:50:03.739720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8435d9ca9f56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reddit_kind', sa.String(length=2), nullable=False),
    sa.Column('reddit_id', sa.String(length=20), nullable=False),
    sa.Column('reddit_url', sa.String(), nullable=False),
    sa.Column('subreddit', sa.String(length=50), nullable=False),
    sa.Column('reddit_created_utc', sa.DateTime(), nullable=False),
    sa.Column('search_keyword', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reddit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reddit_posts')
    # ### end Alembic commands ###
